name: PR test

on:
  push:
    branches:
      - 'delete_pr'

jobs:
  generate-xlt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PATH
      run: |
        echo "/usr/local/bin" >> $GITHUB_PATH
  
    - name: Setup Config
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Fetch All Branches
      run: git fetch --all

    - name: Create Update Branch If Needed
      run: |
        if git ls-remote --exit-code --heads origin pr_test2; then
          git checkout pr_test2
          git pull  --set-upstream origin pr_test2
          echo "Branch already existed"
        else
          git checkout -b pr_test2
          git push origin pr_test2
          echo "Branch made"
        fi

    - name: Test file
      run: |
        echo "HI this is test file2" >> test.txt
        git add .
        git commit -m "Test file"
        git commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m "Test file"
        # git push --set-upstream origin pr_test2

    - name: Create Pull Request
      env:
        NODE_NO_WARNINGS: 1
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ github.TOKEN }}
        branch: pr_test
        title: "PR test"
        body: "PR test - body"
        base: main
     
  