name: PR test

on:
  push:
    branches:
      - 'delete_pr'

jobs:
  generate-xlt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PATH
      run: |
        echo "/usr/local/bin" >> $GITHUB_PATH
  
    - name: Setup Config
      run: |
        git config --global user.email "sjw03151@naver.com"
        git config --global user.name "JS0224"

    - name: Fetch All Branches
      run: git fetch --all

    - name: Delete PR
      env:
        NODE_NO_WARNINGS: 1
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api \
        --method DELETE \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/${{ env. GITHUB_REPOSITORY }}/pulls/comments/1720926727
      

