name: PR test

on:
  push:
    branches:
      - 'delete_pr'

jobs:
  generate-xlt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PATH
      run: |
        echo "/usr/local/bin" >> $GITHUB_PATH
  
    - name: Setup Config
      run: |
        git config --global user.email "sjw03151@naver.com"
        git config --global user.name "JS0224"

    - name: Fetch All Branches
      run: git fetch --all

    - name: Delete PR
      env:
        NODE_NO_WARNINGS: 1
        GH_TOKEN: ${{ github.token }}
      run: |
        # gh api \
        # --method DELETE \
        # -H "Accept: application/vnd.github+json" \
        # -H "X-GitHub-Api-Version: 2022-11-28" \
        # /repos/${{ github.repository }}/pulls/comments/2244256988
        gh api \
        --method DELETE \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        --hostname github.com \
        /repos/${{ github.repository }}/issues/comments/2295301532


#https://github.com/JS0224/graphic-project/pull/1#issuecomment-2295180880
#https://github.com/JS0224/graphic-project/pull/1#pullrequestreview-2244256988
#https://github.com/JS0224/graphic-project/pull/1#pullrequestreview-2244257045
#https://github.com/JS0224/graphic-project/pull/1#discussion_r1720934250
